[package]
name = "arduino_i2c"
version = "0.1.0"
edition = "2021"
authors = ["E³"]
description = "Smart alarm system"

[dependencies]
rppal = "0.22.1" # Bibliothèque standard pour GPIO/I2C sur RPi
anyhow = "1.0" # Pour une gestion d'erreur simplifiée
bitflags = "2.10.0"
ratatui = "0.30.0"
crossterm = "0.29.0"
log = "0.4.29"
lazy_static = "1.5.0"
rusqlite = { version = "0.32.0", features = ["bundled"] }
chrono = "0.4"
clap = { version = "4.5.53", features = ["derive"] }
env_logger = "0.11.8"
